POST http://localhost:3005/api/courses/programming HTTP/1.1
Content-Type: application/json

{
    "id": 4,    
    "title": "Learn Node.js",
    "language": "javascript",
    "views": 45676,
    "level": "basic"        
}

###

PUT http://localhost:3005/api/courses/programming/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "title": "Middle Python with projects",
    "language": "python",
    "views": 123996,
    "level": "middle"
}

###

PATCH http://localhost:3005/api/courses/programming/2 HTTP/1.1
Content-Type: application/json

{
    "title": "Middle Python with projects",
    "views": 123996
}

###

DELETE  http://localhost:3005/api/courses/programming/1 HTTP/1.1